before_install: gem install bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - "sed -i 's/SET lock_timeout = 0;//g' db/structure.sql"

services:
  - postgresql

language: ruby
rvm:
  - 2.4.3

addons:
  postgresql: "9.6"