before_install: gem install bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql

language: ruby
rvm:
  - 2.6.4

addons:
  postgresql: "9.6"