version: "3.3"
services:
  db:
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev
#    volumes:
#      - ./Docker:/var/tmp/docker