"""initial schema

Revision ID: 1858046133a8
Revises: 
Create Date: 2026-05-15 07:55:19.545044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1858046133a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produced_cpp_type_id', sa.Integer(), nullable=False),
    sa.Column('nb_runs', sa.Integer(), nullable=False),
    sa.Column('prod_qtt', sa.Integer(), nullable=False),
    sa.Column('cpp_blueprint_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpp_blueprint_id'),
    sa.UniqueConstraint('produced_cpp_type_id')
    )
    op.create_table('constants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('libe', sa.String(), nullable=False),
    sa.Column('f_value', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libe')
    )
    op.create_table('crontabs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cron_name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('last_updates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('update_type', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('cpp_market_group_id', sa.Integer(), nullable=False),
    sa.Column('cpp_parent_market_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['market_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpp_market_group_id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpp_region_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpp_region_id')
    )
    op.create_table('universe_regions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cpp_region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('orders_pages_count', sa.Integer(), nullable=False),
    sa.Column('market_items', sa.Text(), nullable=False),
    sa.Column('market_items_count', sa.Integer(), nullable=False),
    sa.Column('download_process_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpp_region_id')
    )
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eve_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpp_eve_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('market_group_id', sa.Integer(), nullable=True),
    sa.Column('blueprint_id', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('production_level', sa.Integer(), nullable=True),
    sa.Column('base_item', sa.Boolean(), nullable=False),
    sa.Column('cpp_market_adjusted_price', sa.Float(), nullable=True),
    sa.Column('cpp_market_average_price', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('market_group_path', sa.Text(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('packaged_volume', sa.Float(), nullable=True),
    sa.Column('weekly_avg_price', sa.Float(), nullable=True),
    sa.Column('faction', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ),
    sa.ForeignKeyConstraint(['market_group_id'], ['market_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('trade_hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eve_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('inner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eve_system_id')
    )
    op.create_table('universe_constellations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cpp_constellation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('universe_region_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['universe_region_id'], ['universe_regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpp_constellation_id')
    )
    op.create_table('blueprint_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.Column('required_qtt', sa.Integer(), nullable=False),
    sa.Column('eve_item_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buy_orders_analytics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trade_hub_id', sa.BigInteger(), nullable=False),
    sa.Column('eve_item_id', sa.BigInteger(), nullable=False),
    sa.Column('approx_max_price', sa.Float(), nullable=True),
    sa.Column('over_approx_max_price_volume', sa.BigInteger(), nullable=True),
    sa.Column('single_unit_cost', sa.Float(), nullable=True),
    sa.Column('single_unit_margin', sa.Float(), nullable=True),
    sa.Column('estimated_volume_margin', sa.Float(), nullable=True),
    sa.Column('per_job_margin', sa.Float(), nullable=True),
    sa.Column('per_job_run_margin', sa.Float(), nullable=True),
    sa.Column('final_margin', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eve_market_histories_groups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('eve_item_id', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('highest', sa.Float(), nullable=True),
    sa.Column('lowest', sa.Float(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('universe_region_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['universe_region_id'], ['universe_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices_advices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eve_item_id', sa.Integer(), nullable=False),
    sa.Column('trade_hub_id', sa.Integer(), nullable=False),
    sa.Column('vol_month', sa.BigInteger(), nullable=True),
    sa.Column('avg_price_month', sa.Float(), nullable=True),
    sa.Column('immediate_montly_pcent', sa.Float(), nullable=True),
    sa.Column('margin_percent', sa.Float(), nullable=True),
    sa.Column('avg_price_week', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices_mins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eve_item_id', sa.Integer(), nullable=True),
    sa.Column('trade_hub_id', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_trade_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trade_hub_id', sa.BigInteger(), nullable=False),
    sa.Column('eve_item_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('is_buy_order', sa.Boolean(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.Column('volume_remain', sa.BigInteger(), nullable=False),
    sa.Column('volume_total', sa.BigInteger(), nullable=False),
    sa.Column('min_volume', sa.BigInteger(), nullable=False),
    sa.Column('touched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('sales_finals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('trade_hub_id', sa.BigInteger(), nullable=False),
    sa.Column('eve_item_id', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_hub_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cpp_station_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universe_systems',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cpp_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trade_hub', sa.Boolean(), nullable=False),
    sa.Column('cpp_star_id', sa.Integer(), nullable=True),
    sa.Column('security_class', sa.String(), nullable=True),
    sa.Column('security_status', sa.Float(), nullable=False),
    sa.Column('kill_stats_current_month', sa.Integer(), nullable=False),
    sa.Column('kill_stats_last_month', sa.Integer(), nullable=False),
    sa.Column('universe_constellation_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['universe_constellation_id'], ['universe_constellations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpp_system_id')
    )
    op.create_table('weekly_price_details',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('eve_item_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_hub_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('weighted_avg_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cpp_structure_id', sa.BigInteger(), nullable=False),
    sa.Column('forbidden', sa.Boolean(), nullable=False),
    sa.Column('universe_system_id', sa.BigInteger(), nullable=True),
    sa.Column('orders_count_pages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['universe_system_id'], ['universe_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpp_structure_id')
    )
    op.create_table('universe_stations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cpp_station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('services', sa.Text(), nullable=False),
    sa.Column('office_rental_cost', sa.Float(), nullable=False),
    sa.Column('security_status', sa.Float(), nullable=True),
    sa.Column('jita_distance', sa.Integer(), nullable=True),
    sa.Column('industry_costs_indices', sa.Text(), nullable=True),
    sa.Column('universe_system_id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['universe_system_id'], ['universe_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpp_station_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('expires_on', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('renew_token', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('batch_cap', sa.Boolean(), nullable=False),
    sa.Column('batch_cap_multiplier', sa.Integer(), nullable=False),
    sa.Column('vol_month_pcent', sa.Integer(), nullable=False),
    sa.Column('min_pcent_for_advice', sa.Integer(), nullable=False),
    sa.Column('min_amount_for_advice', sa.Integer(), nullable=False),
    sa.Column('remove_occuped_places', sa.Boolean(), nullable=True),
    sa.Column('watch_my_prices', sa.Boolean(), nullable=True),
    sa.Column('last_changes_in_choices', sa.DateTime(), nullable=True),
    sa.Column('download_assets_running', sa.Boolean(), nullable=False),
    sa.Column('last_assets_download', sa.DateTime(), nullable=True),
    sa.Column('download_orders_running', sa.Boolean(), nullable=False),
    sa.Column('last_orders_download', sa.DateTime(), nullable=True),
    sa.Column('download_blueprints_running', sa.Boolean(), nullable=False),
    sa.Column('last_blueprints_download', sa.DateTime(), nullable=True),
    sa.Column('selected_assets_station_id', sa.BigInteger(), nullable=True),
    sa.Column('last_duplication_receiver_id', sa.Integer(), nullable=True),
    sa.Column('sales_orders_show_margin_min', sa.Integer(), nullable=True),
    sa.Column('initialization_finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['selected_assets_station_id'], ['universe_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blueprint_modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('blueprint_id', sa.BigInteger(), nullable=False),
    sa.Column('percent_modification_value', sa.Float(), nullable=False),
    sa.Column('touched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bpc_assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('universe_station_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('touched', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('eve_item_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['universe_station_id'], ['universe_stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bpc_assets_stations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('universe_station_id', sa.BigInteger(), nullable=False),
    sa.Column('touched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['universe_station_id'], ['universe_stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eve_items_saved_lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('saved_ids', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eve_items_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('eve_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trade_hub_id', sa.Integer(), nullable=False),
    sa.Column('eve_item_id', sa.Integer(), nullable=False),
    sa.Column('runs_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_hubs_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trade_hub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sale_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eve_item_id', sa.Integer(), nullable=False),
    sa.Column('trade_hub_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eve_item_id'], ['eve_items.id'], ),
    sa.ForeignKeyConstraint(['trade_hub_id'], ['trade_hubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_to_user_duplication_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('duplication_type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_user_duplication_requests')
    op.drop_table('user_sale_orders')
    op.drop_table('trade_hubs_users')
    op.drop_table('production_lists')
    op.drop_table('eve_items_users')
    op.drop_table('eve_items_saved_lists')
    op.drop_table('bpc_assets_stations')
    op.drop_table('bpc_assets')
    op.drop_table('blueprint_modifications')
    op.drop_table('users')
    op.drop_table('universe_stations')
    op.drop_table('structures')
    op.drop_table('weekly_price_details')
    op.drop_table('universe_systems')
    op.drop_table('stations')
    op.drop_table('sales_finals')
    op.drop_table('public_trade_orders')
    op.drop_table('prices_mins')
    op.drop_table('prices_advices')
    op.drop_table('eve_market_histories_groups')
    op.drop_table('buy_orders_analytics')
    op.drop_table('blueprint_materials')
    op.drop_table('universe_constellations')
    op.drop_table('trade_hubs')
    op.drop_table('eve_items')
    op.drop_table('user_activity_logs')
    op.drop_table('universe_regions')
    op.drop_table('regions')
    op.drop_table('market_groups')
    op.drop_table('last_updates')
    op.drop_table('crontabs')
    op.drop_table('constants')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
