development:
  adapter: postgresql
  encoding: unicode
  database: eve_business_server_dev
  pool: 5
  username: ced

test:
  adapter: postgresql
  encoding: unicode
  database: eve_business_server_test
  pool: 5
  username: ced