development:
  adapter: postgresql
  encoding: unicode
  database: dev
  pool: 5
  username: dev
  password: dev
  host: localhost
  port: 5436

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: test
  password: test
  host: localhost
  port: 5436