development:
  adapter: postgresql
  encoding: unicode
  database: dev
  pool: 5
  username: dev
  password: dev
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: eve_business_server_test
  pool: 5
  username: ced