development:
  adapter: postgresql
  encoding: unicode
  database: eve_business_server_dev
  pool: 5
  username: eve_business_server
  password: 123456
  #schema_search_path: :dev

test:
  adapter: postgresql
  encoding: unicode
  database: eve_business_server_test
  pool: 5
  username: eve_business_server
  password: 123456
  #schema_search_path: :test

cpp_original_data:
  adapter: sqlite3
  database: work/eve.db
  pool: 5
  timeout: 5000