getTree = ->
# Some logic to retrieve, or generate tree structure
  $.get '/items_tree.json', ( json_data ) ->
    console.log( json_data )
    # data = JSON.parse( json_data )
    # console.log( data )
    $('#tree').treeview data: json_data, showCheckbox: true, levels: 0
    # $('#tree').treeview('collapseAll', { silent: true })


$(document).ready ->
  # TODO : only if in edit view, use an hidden
  console.log( 'getting tree')
  getTree()

# ---
# generated by js2coffee 2.2.0