#!/usr/bin/env python3
"""Update EveItem.cost from Jita sell orders, processing manufacturing levels bottom-up."""
import json
import os
import sys
import time
from typing import Optional
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import setup_logging
import logging
setup_logging()
logger = logging.getLogger(__name__)

from sqlalchemy import text
from evebs.extensions import db
from evebs.models import EveItem, UniverseSystem, Constant

# Path to the pre-built manufacturing tree (generated by data/build_manufacturing_tree.py)
MANUFACTURING_TREE = os.path.join(os.path.dirname(__file__), '..', 'data', 'manufacturing_tree.json')
# EVE Online system ID for Jita 4-4 — the main trade hub used as reference market
JITA_SYSTEM_ID = 30000142
# Minimum volume threshold: we want a price that would let us buy this many units in one pass
TARGET_QTY = 1000
# Log a progress line after this many items processed within a level
LOG_EVERY = 1000


def _load_jita_prices(jita_hub_id: int) -> dict[int, list[tuple[float, int]]]:
    """Fetch the 10 cheapest Jita sell orders per item in a single query.

    Uses a window function to rank sell orders by price within each item, then
    keeps only the top 10. This avoids one query per item (N+1 problem).

    Args:
        jita_hub_id: Database primary key of the Jita TradeHub row.

    Returns:
        Mapping of eve_item_id → list of (price, volume_remain) tuples,
        sorted ascending by price (guaranteed by the ORDER BY in the window).
    """
    rows = db.session.execute(text("""
        SELECT eve_item_id, price, volume_remain
        FROM (
            -- Rank sell orders cheapest-first within each item
            SELECT eve_item_id, price, volume_remain,
                   ROW_NUMBER() OVER (PARTITION BY eve_item_id ORDER BY price) AS rn
            FROM public_trade_orders
            WHERE universe_system_id = :hub_id AND is_buy_order = FALSE
        ) sub
        WHERE rn <= 10
    """), {'hub_id': jita_hub_id}).fetchall()

    # Group rows by item — order is preserved from the ORDER BY in the window
    prices: dict[int, list[tuple[float, int]]] = {}
    for eve_item_id, price, volume in rows:
        prices.setdefault(eve_item_id, []).append((price, volume))
    return prices


def _compute_vwap(orders: list[tuple[float, int]]) -> Optional[float]:
    """Compute the volume-weighted average price (VWAP) to fill up to TARGET_QTY units.

    Walks sell orders from cheapest to most expensive, consuming volume until
    TARGET_QTY units are filled or all orders are exhausted. If total available
    volume is below TARGET_QTY the VWAP is computed over what is available
    (effectively a weighted average of all visible orders).

    Args:
        orders: List of (price, volume_remain) tuples sorted by price ascending.

    Returns:
        VWAP as a float, or None if no orders are available.
    """
    if not orders:
        return None

    total_volume = sum(v for _, v in orders)
    # Cap fill at what the market can actually supply
    fill = min(TARGET_QTY, total_volume)

    remaining = fill
    total_cost = 0.0
    for price, volume in orders:
        take = min(volume, remaining)
        total_cost += take * price
        remaining -= take
        if remaining <= 0:
            break

    return total_cost / fill


def update_eve_item_cost() -> None:
    """Update EveItem.cost for all items using Jita sell-order prices.

    Processing order:
      1. Level-0 items (not in the manufacturing tree, i.e. raw materials):
         cost = VWAP of the 10 cheapest Jita sell orders for that item.
      2. Level-1 … level-n manufactured items (ascending):
         cost = sum(component.cost × quantity) × taxes / prod_qty
         Components at level n-1 are guaranteed to be updated before level n.

    Items whose components have unknown costs receive cost = None so they are
    excluded from downstream margin calculations rather than silently wrong.
    """
    t_start = time.time()
    logger.info('=== update_eve_item_cost started ===')

    # Resolve Jita's internal DB id — needed to filter public_trade_orders
    jita = UniverseSystem.query.filter_by(cpp_system_id=JITA_SYSTEM_ID, trade_hub=True).first()
    if not jita:
        logger.error('Jita trade hub system not found (cpp_system_id=%d).', JITA_SYSTEM_ID)
        return
    jita_hub_id: int = jita.id

    # Load the static manufacturing tree built by data/build_manufacturing_tree.py
    t = time.time()
    with open(MANUFACTURING_TREE) as f:
        tree: dict = json.load(f)
    logger.debug('Manufacturing tree loaded: %d entries in %.2fs.', len(tree), time.time() - t)

    # Taxes multiplier applied to every manufactured item's cost
    taxes_const = Constant.query.filter_by(libe='taxes').first()
    taxes: float = taxes_const.f_value if taxes_const else 1.0

    # Build a lookup keyed by EVE Online typeID for O(1) access during cost propagation
    t = time.time()
    item_map: dict[int, EveItem] = {item.id: item for item in EveItem.query.all()}
    logger.debug('Item map built: %d items in %.2fs.', len(item_map), time.time() - t)

    # Pre-load all Jita sell prices in one query instead of per-item queries
    t = time.time()
    jita_prices: dict[int, list[tuple[float, int]]] = _load_jita_prices(jita_hub_id)
    logger.info('Jita prices loaded: %d items in %.2fs.', len(jita_prices), time.time() - t)

    # --- Level 0: raw materials not present in the manufacturing tree ---
    # These items have no blueprint; their cost is simply what it costs to buy
    # them on the Jita market.
    t = time.time()
    t_checkpoint = time.time()
    tree_ids: set[int] = {int(k) for k in tree}
    base_items = [item for item in item_map.values() if item.id not in tree_ids]
    for i, item in enumerate(base_items, 1):
        item.cost = _compute_vwap(jita_prices.get(item.id, []))
        if i % LOG_EVERY == 0:
            logger.info('Level 0: %d items updated in %.2fs.', i, time.time() - t_checkpoint)
            t_checkpoint = time.time()
    db.session.commit()
    logger.info('Level 0 done: %d base items updated in %.2fs.', len(base_items), time.time() - t)

    # --- Levels 1…n: manufactured items ---
    # Group tree entries by manufacturing_level so we can process them in ascending
    # order; this guarantees every component's cost is set before we compute the
    # cost of items that depend on it.
    by_level: dict[int, list[tuple[int, dict]]] = {}
    for type_id_str, entry in tree.items():
        lvl = entry['manufacturing_level']
        by_level.setdefault(lvl, []).append((int(type_id_str), entry))

    for level in sorted(by_level):
        t = time.time()
        t_checkpoint = time.time()
        batch = by_level[level]
        processed = 0
        for type_id, entry in batch:
            item = item_map.get(type_id)
            if not item:
                # Item exists in the static tree but not in our DB — skip silently
                continue

            chain: dict = entry['chain']
            prod_qty: int = entry['prod_qty']
            total = 0.0
            unknown = False

            # Sum up the cost of every direct component weighted by required quantity
            for mat_id_str, mat in chain.items():
                comp = item_map.get(int(mat_id_str))
                if comp is None or comp.cost is None:
                    # Missing or unpriced component — mark cost as unknown
                    unknown = True
                    break
                total += comp.cost * mat['quantity']

            # Apply production taxes and normalise by the number of units produced per run
            item.cost = None if unknown else (total * taxes / prod_qty)
            processed += 1
            if processed % LOG_EVERY == 0:
                logger.info('Level %d: %d items updated in %.2fs.', level, processed, time.time() - t_checkpoint)
                t_checkpoint = time.time()

        db.session.commit()
        logger.info('Level %d done: %d items updated in %.2fs.', level, processed, time.time() - t)

    logger.info('=== update_eve_item_cost finished in %.2fs ===', time.time() - t_start)


if __name__ == '__main__':
    from app import app
    with app.app_context():
        update_eve_item_cost()
