from datetime import datetime

from evebs.extensions import db


class Blueprint(db.Model):
    __tablename__ = 'blueprints'

    id = db.Column(db.Integer, primary_key=True, autoincrement=False)
    produced_type_id = db.Column(db.Integer, nullable=False, unique=True)
    nb_runs = db.Column(db.Integer, nullable=False)
    prod_qtt = db.Column(db.Integer, nullable=False)
    name = db.Column(db.String, nullable=False)
    activity_type = db.Column(db.String(20), nullable=False, server_default='manufacturing')
    manufacturing_cost = db.Column(db.Float, nullable=True)
    # Recursive bill-of-materials tree for this blueprint, populated by
    # process/update_blueprints.py from data/manufacturing_tree.json (which is
    # itself generated by data/build_manufacturing_tree.py from the EVE SDE).
    #
    # Top-level structure — one entry per DIRECT material:
    #
    #   {
    #     "<mat_type_id_str>": {          # str(EVE typeID) of the required material
    #       "name":     "<item name>",    # human-readable material name (English)
    #       "quantity": <int>,            # units of this material needed for ONE batch
    #                                     # (i.e. to produce prod_qtt units of the item)
    #       "chain": {                    # recursive sub-tree: if this material is itself
    #                                     # manufacturable, its own BOM is nested here;
    #                                     # empty dict {} for raw/un-manufacturable materials
    #         "<sub_mat_type_id_str>": {
    #           "name":     "...",
    #           "quantity": <int>,
    #           "chain":    { ... }       # continues recursively
    #         },
    #         ...
    #       }
    #     },
    #     ...
    #   }
    #
    # Cost calculation uses ONLY the direct (top-level) materials:
    #   manufacturing_cost = sum(int(mat_id) quantity × jita_price)
    #                        for mat_id, entry in manufacturing_tree.items()
    #   per_unit_cost = manufacturing_cost / prod_qtt
    #
    # The nested chain is stored for display purposes (components-to-buy screen)
    # and is NOT used in the cost formula — callers decide whether to buy
    # sub-components or manufacture them.
    #
    # Key type: always str (JSON object keys are strings); cast with int(key)
    # to get the EVE typeID for DB lookups.
    #
    # Consumers:
    #   routes/production_costs.py  — iterates top-level keys to show the BOM table
    #   routes/buy_orders.py        — iterates top-level keys to compute live manuf. cost
    #   process/update_blueprints.py — writes this field from manufacturing_tree.json
    manufacturing_tree = db.Column(db.JSON, nullable=True)
    # blueprints.id of the T1 blueprint this T2 was invented from (e.g. Hail ← Barrage).
    # No DB-level FK — not all T1 blueprints exist in our table; the relationship
    # is resolved in software. NULL for T1/reaction blueprints.
    is_invented_from_id = db.Column(db.Integer, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    eve_item = db.relationship('EveItem', back_populates='blueprint', uselist=False)
    blueprint_modifications = db.relationship('BlueprintModification', back_populates='blueprint')
    users = db.relationship('User', secondary='user_blueprints', back_populates='blueprints')

    @property
    def batch_elements_count(self):
        return self.prod_qtt * self.nb_runs
